name: 'Read changelog'
description: 'Reading changelog file'
author: 'embedd-actions'

# Add your action's branding here. This will appear on the GitHub Marketplace.
# branding:
#   icon: 'heart'
#   color: 'red'

inputs:
  changelogfile: # id of input
    description: 'File for handling'
    required: true
    default: 'none'
  tag:
    description: 'Search tag'
    required: true
    default: 'none'
outputs:
  content: # id of output
    description: 'Changelog for search tag'

runs:
  using: node20
  main: dist/index.js
